name: ci

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: phuochungus/pycil
      -
        name: Deploy on Render
        run: curl -X GET "https://api.render.com/deploy/srv-cpi94ja1hbls73bed200?key=${{ secrets.RENDER_API_KEY }}"

